services:
  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=e-comm'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
